version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: dockerfiles/fastapi.dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/react.dockerfile
    ports:
    - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: "postgres:15"
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data